### ISSUE TITLE
System.PlatformNotSupportedException: This action can be performed only on Windows operating system.  

### ISSUE THREAD

**Issue by tommy-mtwi** [DevExpress-Examples/how-to-export-a-pdf-document-to-multi-page-tiff-and-bitmap#1]
is there anyway to run this on Linux?

Bitmap _bitmap = pdfDocumentProcessor.CreateBitmap(i, largestEdgeLength);

System.PlatformNotSupportedException: This action can be performed only on Windows operating system.  
   at DevExpress.Pdf.PdfDocumentProcessor.CheckPlarformSpecificOperationAvailability()  
   at DevExpress.Pdf.PdfDocumentProcessor.CreateBitmap(Int32 pageNumber, Int32 largestEdgeLength)

**Comment by YuliaDX** [comment]
Hi,

Exporting PDF content to an image using the PDF Document API library is not supported on Linux and Mac OS.

Please refer to the [Office File API for .NET Core - Limitations](https://docs.devexpress.com/OfficeFileAPI/14911/office-file-api?p=netstandard#limitations) article for more information.
